// Generated by CoffeeScript 1.10.0

/*
Created by Robsdedude on 01/10/2017
Virtual gamepad application
 */

(function() {
  var config, earlyDeathCount, forever, server, winston;

  forever = require('forever-monitor');

  config = require('./config.json');

  winston = require('winston');

  winston.level = config.logLevel;

  server = new forever.Monitor('server.js', {
    max: Infinity,
    args: []
  });

  server.on('exit', function() {
    return winston.log('error', 'server.js has exited (gave up to restart)');
  });

  earlyDeathCount = 0;

  server.on('exit:code', function() {
    var diedAfter;
    diedAfter = Date.now() - server.ctime;
    winston.log('info', 'diedAfter:', diedAfter);
    earlyDeathCount = diedAfter < 5000 ? earlyDeathCount + 1 : 0;
    winston.log('info', 'earlyDeathCount:', earlyDeathCount);
    if (earlyDeathCount >= 3) {
      winston.log('error', 'Died too often too fast.');
      return server.stop();
    }
  });

  server.on('restart', function() {
    return winston.log('error', 'Forever restarting script for ' + server.times + ' time');
  });

  server.start();

}).call(this);
