// Generated by CoffeeScript 1.10.0

/*
Virtual trackpad hub class
 */

(function() {
  var trackpad, virtual_trackpad_hub;

  trackpad = require('./virtual_trackpad');

  virtual_trackpad_hub = (function() {
    function virtual_trackpad_hub() {
      this.trackpads = [];
    }

    virtual_trackpad_hub.prototype.connectTrackpad = function(callback) {
      var trackpadId;
      trackpadId = this.trackpads.length;
      this.trackpads[trackpadId] = new trackpad();
      return this.trackpads[trackpadId].connect(function() {
        return callback(trackpadId);
      }, function(err) {
        return callback(-1);
      });
    };

    virtual_trackpad_hub.prototype.disconnectTrackpad = function(trackpadId, callback) {
      if (this.trackpads[trackpadId]) {
        return this.trackpads[trackpadId].disconnect((function(_this) {
          return function() {
            _this.trackpads[trackpadId] = void 0;
            return callback();
          };
        })(this));
      }
    };

    virtual_trackpad_hub.prototype.sendEvent = function(trackpadId, event) {
      if (this.trackpads[trackpadId]) {
        return this.trackpads[trackpadId].sendEvent(event);
      }
    };

    return virtual_trackpad_hub;

  })();

  module.exports = virtual_trackpad_hub;

}).call(this);
