// Generated by CoffeeScript 1.10.0

/*
Created by roba91 on 15/08/2016
Virtual keyboard class
 */

(function() {
  var fs, ioctl, log, uinput, uinputStructs, virtual_keyboard;

  fs = require('fs');

  ioctl = require('ioctl');

  uinput = require('../lib/uinput');

  uinputStructs = require('../lib/uinput_structs');

  log = require('../lib/log');

  virtual_keyboard = (function() {
    function virtual_keyboard() {}

    virtual_keyboard.prototype.connect = function(callback, error, retry) {
      if (retry == null) {
        retry = 0;
      }
      return fs.open('/dev/uinput', 'w+', (function(_this) {
        return function(err, fd) {
          var i, j, uidev, uidev_buffer;
          if (err) {
            log('error', "Error on opening /dev/uinput:\n", err);
            return error(err);
          } else {
            _this.fd = fd;
            ioctl(_this.fd, uinput.UI_SET_EVBIT, uinput.EV_KEY);
            for (i = j = 0; j <= 255; i = ++j) {
              ioctl(_this.fd, uinput.UI_SET_KEYBIT, i);
            }
            uidev = new uinputStructs.uinput_user_dev;
            uidev_buffer = uidev.ref();
            uidev_buffer.fill(0);
            uidev.name = Array.from("Virtual keyboard");
            uidev.id.bustype = uinput.BUS_USB;
            uidev.id.vendor = 0x3;
            uidev.id.product = 0x4;
            uidev.id.version = 1;
            return fs.write(_this.fd, uidev_buffer, 0, uidev_buffer.length, null, function(err) {
              var error1;
              if (err) {
                log('error', "Error on init keyboard write:\n", err);
                return error(err);
              } else {
                try {
                  ioctl(_this.fd, uinput.UI_DEV_CREATE);
                  return callback();
                } catch (error1) {
                  error = error1;
                  log('error', "Error on keyboard dev creation:\n", err);
                  fs.closeSync(_this.fd);
                  _this.fd = void 0;
                  if (retry < 5) {
                    log('info', "Retry to create keyboard");
                    return _this.connect(callback, error, retry + 1);
                  } else {
                    log('error', "Gave up on creating device");
                    return error(err);
                  }
                }
              }
            });
          }
        };
      })(this));
    };

    virtual_keyboard.prototype.disconnect = function(callback) {
      if (this.fd) {
        ioctl(this.fd, uinput.UI_DEV_DESTROY);
        fs.closeSync(this.fd);
        this.fd = void 0;
        return callback();
      }
    };

    virtual_keyboard.prototype.sendEvent = function(event) {
      var ev, ev_buffer, ev_end, ev_end_buffer;
      log('debug', event);
      if (this.fd) {
        ev = new uinputStructs.input_event;
        ev.type = event.type;
        ev.code = event.code;
        ev.value = event.value;
        ev.time.tv_sec = Math.round(Date.now() / 1000);
        ev.time.tv_usec = Math.round(Date.now() % 1000 * 1000);
        ev_buffer = ev.ref();
        ev_end = new uinputStructs.input_event;
        ev_end.type = 0;
        ev_end.code = 0;
        ev_end.value = 0;
        ev_end.time.tv_sec = Math.round(Date.now() / 1000);
        ev_end.time.tv_usec = Math.round(Date.now() % 1000 * 1000);
        ev_end_buffer = ev_end.ref();
        fs.writeSync(this.fd, ev_buffer, 0, ev_buffer.length, null);
        return fs.writeSync(this.fd, ev_end_buffer, 0, ev_end_buffer.length, null);
      }
    };

    return virtual_keyboard;

  })();

  module.exports = virtual_keyboard;

}).call(this);
